version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - run: npm install
    - run: npm run test
    - run: sleep 60


workflows:
  version: 2
  workflow:
    jobs:
    - build

